### ISSUE TITLE
룩북 만들기 페이지 작업

### ISSUE THREAD

**Issue by presentKey** [FashionForecast/FashionForecast-client#111]
### 📄 Describe

룩북 만들기 페이지 작업

### ✅ Tasks

- [x] 경로 `/user/lookbook/create?type=1`
   - type은 1~8 값을 가진다.
- [x] `TypeHeadline`
   - 계절 type에 해당하는 문구과 배경색을 가진다.
- [x] `Showcase`
   - [x] 상의와 하의 carousel 좌우 스와이핑
   - [x] 상의 또는 하의 옷 선택 시, 포커싱이 토글된다.
   - [x] 계절 type에 해당하는 대표 옷이 default로 선택되어 있다.
- [x] `ColorPalette`
   - [x]  옷 포커싱 시, 상의 색상 또는 하의 색상을 선택할 수 있다.
   - [x] 색상 선택 후 옷 종류 변경 시, 선택된 색상 유지
   - [x] default 색상은 흰색
   - [x] ColorPalette 영역 스크롤 가능 시, 영역을 위로 Drawer 가능
      - [x] Drawer된 경우, 옷 고르기 버튼 렌더링
      - [x] 옷 고르기 버튼 클릭 시, 영역이 기존 위치로 돌아간다
