### ISSUE TITLE
기본 위치 설정

### ISSUE THREAD

**Issue by presentKey** [FashionForecast/FashionForecast-client#121]
### 📄 Describe

- `4.3.1` 기본 위치 설정
   - 현재 위치 (default)
   - 직접 설정  

### ✅ Tasks

- [x] 기본 위치 설정
   - [x] 클릭 시, `/search` 페이지로 이동
   - [x] 검색 목록 클릭 시, 직접 설정 변경
   - [x] 현재 위치로 설정하기 버튼 클릭 시, 현재 위치 설정 변경
- [x] 설정 완료 시, 설정 페이지로 이동
- [x] 사용자 지역 설정 값으로 현재 위치 설정
