### ISSUE TITLE
UIUX 개선

### ISSUE THREAD

**Issue by presentKey** [FashionForecast/FashionForecast-client#135]
### 📄 Describe

UIUX 개선

### ✅ Tasks

- [x] 회원 성별 설정 값 표시
- [x] 검색 페이지 뒤로가기 조건 수정
- [x] 시간대 변경 시, 스낵바 노출
- [x] 이용약관 / 개인정보처리방침 추가
