### ISSUE TITLE
지역 위치 저장, 삭제 구현

### ISSUE THREAD

**Issue by presentKey** [FashionForecast/FashionForecast-client#15]
### 📄 Describe

지역 위치 저장, 삭제 구현

### ✅ Tasks

- 위치 저장
  - [ ] 검색 목록 아이템 클릭 시, 해당 지역 저장 

- 위치 삭제 
  - [ ] 검색 목록 아이템 클릭 시, 저장된 위치인 경우 하단에 삭제 버튼 렌더링
  - [ ] 로컬 스토리지에서 해당 위치 삭제

- LocationSelector
  - [ ] 랜딩페이지에서 사용자의 저장된 위치 렌더링 
  - [ ] 칩을 짧게 누르면 해당 지역으로 선택
  - [ ] 칩을 길게 누르거나 (+)를 누르면 검색 페이지로 이동
