### ISSUE TITLE
검색 기능 변경

### ISSUE THREAD

**Issue by presentKey** [FashionForecast/FashionForecast-client#36]
### 📄 Describe

1. 검색 기능 변경
- 단어의 첫 번째와 일치하는 경우에만 검색
   - 검색어: `남` 
   - 경기도 `남`양주시 (O)
   - 경기도 성`남`시 (X)

2. 현재 위치로 설정하기
3. 최근 검색어 마크업

### ✅ Tasks

- [x] 검색 기능 변경
- [x] 현재 위치로 설정하기
- [x] 최근 검색어 마크업
