### ISSUE TITLE
디자인 변경 작업

### ISSUE THREAD

**Issue by presentKey** [FashionForecast/FashionForecast-client#48]
### 📄 Describe

디자인 변경 작업

### ✅ Tasks

- [x] 날씨 아이콘 조건 변경
- [x] TextField focus 색상 변경
- [x] 타임라인 기온 width 조정
- [x] AppBar 색상 변경
- [x] 추천 옷 카드 변경
