### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by presentKey** [FashionForecast/FashionForecast-client#6]
### 🤔 Describe

- 라이브러리 기본 세팅
- 폴더 세팅
- material ui 사용 
   - scss → emotion 변경

### ✅ Tasks

- [x] react-router 세팅
- [x] tanstack-query 세팅
- [x] react-redux 세팅
- [x] material ui 설치
- [x] emotion 세팅
- [x] 폴더 구조
